### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by leryan36** [niklasvieth/polestar-ios-lockscreen-widget#2]
Hi, thank you for sharing your work for the Polestar app. I have followed the instructions to the letter, however, I am getting error message at the end, which I am attaching here. Thank you
![IMG_24B3D988F9DC-1](https://github.com/niklasvieth/polestar-ios-lockscreen-widget/assets/32008098/336a0fa9-2ad2-430d-b244-ddfea0101a7e)

**Comment by niklasvieth** [comment]
Are you sure that your email and password of Tibber are correct?

Please make sure to remove the `<` and `>` and just put the email and password inside the ““ quotation marks.

**Comment by leryan36** [comment]
Thanks!

You are absolutely right, I missed removing the <>.

I appreciate your quick response.

--
Dr Ryan Lemand
Mobile: +971503863377

From: Niklas ***@***.***>
Date: Thursday, 9 November 2023 at 10:26 AM
To: niklasvieth/polestar-ios-lockscreen-widget ***@***.***>
Cc: leryan36 ***@***.***>, Author ***@***.***>
Subject: Re: [niklasvieth/polestar-ios-lockscreen-widget] Bug (Issue #2)

Are you sure that your email and password of Tibber are correct?

Please make sure to remove the < and > and just put the email and password inside the ““ quotation marks.
