### ISSUE TITLE
Tibber data battery error

### ISSUE THREAD

**Issue by Szteffensen** [niklasvieth/polestar-ios-lockscreen-widget#6]
Hi,

The widget has been working perfekt for me.

But now i get this issue :

![IMG_5263](https://github.com/user-attachments/assets/c5fdbcd3-be78-4014-9b7d-d8067e65a194)

Is it a fix for this?

**Comment by niklasvieth** [comment]
Does the polestar website still show your battery status?

Go to 
https://www.polestar.com/de/login/profile
Login and click on your car?

**Comment by Szteffensen** [comment]
![image](https://github.com/user-attachments/assets/5cc95a0c-22c9-4e34-97a1-949aeda4fbfd)


Yes, it still show it here.

**Comment by niklasvieth** [comment]
Can you check again if you maintained the VIN  correctly here 

https://github.com/niklasvieth/polestar-ios-lockscreen-widget/blob/7004c34902960d3d7ea2da03c8da2af8a656a9ce/polestar-lockscreen-widget.js#L11

**Comment by Szteffensen** [comment]
Hi,

That line was not in the script i used.

Have the script been updated?

**Comment by niklasvieth** [comment]
Not very recently but the was an update some months ago. You can update it via scriptdude in scriptable. Just click on the blue script and update. 
You then have to update the top section of the script with your login credentials and the VIN.

**Comment by Szteffensen** [comment]
![IMG_5264](https://github.com/user-attachments/assets/d97ae7d8-4144-4fda-9bbd-897fe3102fd4)

im doing something wrong?

Cant find it here

**Comment by niklasvieth** [comment]
@Szteffensen okay then you can just install it by clicking on this link 

https://scriptdu.de/?name=Polestar%20Lockscreen%20SoC%20Widget&source=https%3A%2F%2Fgist.githubusercontent.com%2Fniklasvieth%2F9cb306b53835a9a283e34b77f0f2513f%2Fraw%2Ff5e29c99e8cc017c0d4fa2f8e825f79031282a2a%2Fpolestar-lockscreen-widget.js&docs=https%3A%2F%2Fgithub.com%2Fniklasvieth%2Fpolestar-ios-lockscreen-widget%2Fblob%2Fmain%2FREADME.md#generator&color=green&icon=battery-half

**Comment by Szteffensen** [comment]
Thanks!

It world again now👍
