### ISSUE TITLE
Lockscreen widget blank after iOS 18 update

### ISSUE THREAD

**Issue by kubusxzx** [niklasvieth/polestar-ios-lockscreen-widget#7]
As per the title, lockscreen widget no longer loads and is “blank” after iOS 18 update. Medium widget still works as usual.

When trying the lockscreen widget from within Scriptable it works fine and there are no errors.

**Comment by niklasvieth** [comment]
Yes I have he same issue at the moment. Seems to be an iOS 18 timeout issue.
Will check but most likely a scriptable fix will be necessary.

**Comment by niklasvieth** [comment]
Although I still like mine better, the Polestar app now features Widget with `v4.13.0` of the app.
https://www.facebook.com/share/v/siHd91zzhXCyRMir/?

**Comment by Stroell** [comment]
Agree, yours is better 👍 
Hope there is a fix for it soon. Really miss it!

**Comment by Stroell** [comment]
Hey,
Is the issue fixed?
For me it still doesn't work with iOS 18.1 and v2.0.1 of your script. 
Thank you ☺️
